services:
#  KEYCLOAK
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.3
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin1
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin1
    ports:
      - "8443:8080"
    networks:
      - ecommerce
    restart: unless-stopped
#  RABBITMQ
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce
    restart: unless-stopped
#  ZIPKIN
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - ecommerce
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ecommerce
    restart: unless-stopped

networks:
  ecommerce:
    driver: bridge

volumes:
  postgres:
  pgadmin:

#  postgres:
#    container_name:  postgres_container
#    image: postgres
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres: /data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      ecommerce
#    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - ecommerce
#    restart: unless-stopped
